---

- name: Create iSCSI LUNs
  include_role:
    name: create_scsi_luns

- name: Get an active Host
  ovirt_hosts_facts:
    auth: "{{ ovirt_auth }}"
    pattern: status = Up

- name: Create iSCSI Storage Domains
  include_tasks: create_domain.yml
  with_items:
    - "{{ scsi_domains }}"
  vars:
    host_name: "{{ ovirt_hosts[0].name }}"

